# Generated by Django 6.1 on 2026-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок статьи", max_length=100, unique=True, verbose_name="Заголовок"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Текст статьи", null=True, verbose_name="Содержимое"),
                ),
                ("preview", models.ImageField(blank=True, null=True, upload_to="previews/", verbose_name="Превью")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Статья опубликована?", verbose_name="Признак публикации"
                    ),
                ),
                ("views_counter", models.PositiveIntegerField(default=0, verbose_name="Счетчик просмотров")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["created_at"],
            },
        ),
    ]
