# Generated by Django 6.1 on 2026-09-10 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category_name",
                    models.CharField(
                        help_text="Наименование категории", max_length=150, unique=True, verbose_name="Категория"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Описание категории", null=True, verbose_name="Описание"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "prod_name",
                    models.CharField(
                        help_text="Наименование продукта", max_length=150, unique=True, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Описание продукта", null=True, verbose_name="Описание"),
                ),
                ("prod_image", models.ImageField(upload_to="images/", verbose_name="Изображение товара")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Цена товара", max_digits=10, verbose_name="Цена товара"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["prod_name", "price", "category", "created_at"],
            },
        ),
    ]
