# Generated by Django 6.1 on 2026-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["category_name"], "verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterField(
            model_name="product",
            name="prod_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Изображение товара"),
        ),
        migrations.AlterField(
            model_name="product",
            name="prod_name",
            field=models.CharField(help_text="Наименование продукта", max_length=150, verbose_name="Наименование"),
        ),
    ]
